apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: mtls
spec:
  domain: {{ .Values.domain }}
  clientTLS:
    clientCA:
      name: router-ca-certs-mtls
    clientCertificatePolicy: Required
    allowedSubjectPatterns:
      - "{{ .Values.commonName }}"
  replicas: 2
  routeSelector:
    matchLabels:
      type: mtls
